# Basic Vector and Matrix Operation with Numpy.

**Problem - 1: Array Creation:**

In [34]:


import numpy as np

# 1. Initialize an empty array with size 2X2.
empty_array = np.empty((2, 2))

# 2. Initialize an all one array with size 4X2.
ones_array = np.ones((4, 2))

# 3. Return a new array of given shape and type, filled with fill value.
fill_value_array = np.full((3, 3), 5)  # Example fill value is 5

# 4. Return a new array of zeros with the same shape and type as a given array.
example_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(example_array)

# 5. Return a new array of ones with the same shape and type as a given array.
ones_like_array = np.ones_like(example_array)

# 6. Convert a list to a NumPy array.
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)

print(f"Empty Array: {empty_array}")
print(f"Ones Array: {ones_array}")
print(f"Fill Value Array: {fill_value_array}")
print(f"Zeros Like Array: {zeros_like_array}")
print(f"Ones Like Array: {ones_like_array}")
print(f"Numpy Array from List: {numpy_array}")


Empty Array: [[1.14e-322 2.52e-322]
 [6.42e-323 1.43e-322]]
Ones Array: [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Fill Value Array: [[5 5 5]
 [5 5 5]
 [5 5 5]]
Zeros Like Array: [[0 0]
 [0 0]]
Ones Like Array: [[1 1]
 [1 1]]
Numpy Array from List: [1 2 3 4]


**Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:**

In [35]:
import numpy as np

# 1. Create an array with values ranging from 10 to 49.
array_1 = np.arange(10, 50)
print(f"Array with values ranging from 10 to 49:\n{array_1}\n")

# 2. Create a 3X3 matrix with values ranging from 0 to 8.
matrix_1 = np.arange(9).reshape(3, 3)
print(f"3x3 matrix with values from 0 to 8:\n{matrix_1}\n")

# 3. Create a 3X3 identity matrix.
identity_matrix = np.eye(3)
print(f"3x3 identity matrix:\n{identity_matrix}\n")

# 4. Create a random array of size 30 and find the mean.
random_array = np.random.random(30)
mean_value = random_array.mean()
print(f"Random array of size 30:\n{random_array}\nMean: {mean_value}\n")

# 5. Create a 10X10 array with random values and find min and max.
random_matrix = np.random.random((10, 10))
min_value = random_matrix.min()
max_value = random_matrix.max()
print(f"10x10 array with random values:\nMinimum: {min_value}\nMaximum: {max_value}\n")

# 6. Create a zero array of size 10 and replace the 5th element with 1.
zero_array = np.zeros(10)
zero_array[4] = 1  # 5th element (index 4)
print(f"Zero array with 5th element replaced by 1:\n{zero_array}\n")

# 7. Reverse an array arr = [1, 2, 0, 0, 4, 0].
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print(f"Reversed array:\n{reversed_arr}\n")

# 8. Create a 2D array with 1 on the border and 0 inside.
rows, cols = 5, 5 # Example size
arr2d = np.ones((rows, cols), dtype=int)
arr2d[1:-1, 1:-1] = 0
print(f"2D array with 1 on the border and 0 inside:\n{arr2d}\n")

# 9. Create an 8X8 matrix and fill it with a checkerboard pattern.
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(f"8x8 Checkerboard pattern:\n{checkerboard}")

Array with values ranging from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 matrix with values from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random array of size 30:
[0.93360963 0.28762351 0.33902713 0.03877361 0.87162853 0.27127059
 0.39614351 0.73776195 0.90439084 0.19968889 0.66123804 0.00516591
 0.87837513 0.35907319 0.47072734 0.8628695  0.03377726 0.98666835
 0.43499432 0.17407657 0.30338944 0.60496784 0.98297469 0.18186143
 0.56602622 0.45614323 0.6328002  0.13882435 0.07584544 0.54605823]
Mean: 0.47785916279243723

10x10 array with random values:
Minimum: 0.0053609479033635
Maximum: 0.9969961194327747

Zero array with 5th element replaced by 1:
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

Reversed array:
[0 4 0 0 2 1]

2D array with 1 on the border and 0 inside:
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]

8x8 Checkerboard

**Problem - 3: Array Operations:**

In [36]:
# prompt: Problem - 3: Array Operations:
# For the following arrays:
# x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
# v = np.array([9,10]) and w = np.array([11,12]);
# Complete all the task using numpy:
# 1. Add the two array.
# 2. Subtract the two array.
# 3. Multiply the array with any integers of your choice.
# 4. Find the square of each element of the array.
# 5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
# 6. Concatenate x(and)y along row and Concatenate v(and)w along column.
# {Hint:try np.concatenate() or np.vstack() functions.
# 7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?
# print too

import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

# 1. Add the two arrays.
print("Addition of x and y:\n", np.add(x, y))

# 2. Subtract the two arrays.
print("\nSubtraction of x and y:\n", np.subtract(x, y))

# 3. Multiply the array with any integer.
print("\nx multiplied by 2:\n", x*2)
print("\ny multiplied by 3:\n", y*3)

# 4. Find the square of each element of the array
print("\nSquare of each element in x:\n", np.square(x))
print("\nSquare of each element in y:\n", np.square(y))

# 5. Find the dot product between v and w, x and v, x and y
print("\nDot product of v and w:", np.dot(v,w))
print("\nDot product of x and v:\n", np.dot(x,v))
print("\nDot product of x and y:\n", np.dot(x,y))

# 6. Concatenate x and y along rows and v and w along columns.
print("\nConcatenate x and y along rows:\n", np.concatenate((x,y), axis=0))
print("\nConcatenate v and w along columns:\n", np.vstack((v,w)))

# 7. Concatenate x and v
print("\nAttempting to concatenate x and v...")
try:
    print(np.concatenate((x,v),axis=0))
except ValueError as e:
    print(f"Error: {e}")
    print("The error occurs because x is a 2x2 matrix and v is a 1x2 vector.  To concatenate them they need compatible dimensions along the specified axis.  You can either reshape v or use vstack/hstack")


Addition of x and y:
 [[ 6  8]
 [10 13]]

Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]

x multiplied by 2:
 [[ 2  4]
 [ 6 10]]

y multiplied by 3:
 [[15 18]
 [21 24]]

Square of each element in x:
 [[ 1  4]
 [ 9 25]]

Square of each element in y:
 [[25 36]
 [49 64]]

Dot product of v and w: 219

Dot product of x and v:
 [29 77]

Dot product of x and y:
 [[19 22]
 [50 58]]

Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate v and w along columns:
 [[ 9 10]
 [11 12]]

Attempting to concatenate x and v...
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
The error occurs because x is a 2x2 matrix and v is a 1x2 vector.  To concatenate them they need compatible dimensions along the specified axis.  You can either reshape v or use vstack/hstack


**Problem - 4: Matrix Operations:**

In [37]:


import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A.A−1 = I.
A_inv = np.linalg.inv(A)
I = np.dot(A, A_inv)
print("A.A−1 =\n", I)

# 2. Prove AB != BA.
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nAB =\n", AB)
print("\nBA =\n", BA)
print("\nAB == BA", np.array_equal(AB, BA)) # Should be False

# 3. Prove (AB)T = BTAT.
AB_T = np.transpose(AB)
B_T = np.transpose(B)
A_T = np.transpose(A)
BT_AT = np.dot(B_T, A_T)
print("\n(AB)T =\n", AB_T)
print("\nBTAT =\n", BT_AT)
print("\n(AB)T == BTAT", np.array_equal(AB_T, BT_AT)) # Should be True


A.A−1 =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

AB =
 [[23 13]
 [51 29]]

BA =
 [[36 44]
 [13 16]]

AB == BA False

(AB)T =
 [[23 51]
 [13 29]]

BTAT =
 [[23 51]
 [13 29]]

(AB)T == BTAT True


# Experiment: How Fast is Numpy?

In [33]:
import numpy as np
import time

**Elements Wise Addition**

In [32]:


# Number of elements in the lists
size = 1_000_000

# Create two Python lists
list1 = list(range(size))
list2 = list(range(size))

# Measure the time taken for element-wise addition using Python lists
start_time = time.time()
list3 = [a + b for a, b in zip(list1, list2)]
end_time = time.time()
list_time = end_time - start_time
print(f"Time taken for list addition: {list_time:.6f} seconds")

# Create two NumPy arrays
array1 = np.arange(size)
array2 = np.arange(size)

# Measure the time taken for element-wise addition using NumPy arrays
start_time = time.time()
array3 = array1 + array2  # Faster element-wise addition with NumPy
end_time = time.time()
numpy_time = end_time - start_time
print(f"Time taken for NumPy array addition: {numpy_time:.6f} seconds")


Time taken for list addition: 0.051502 seconds
Time taken for NumPy array addition: 0.002000 seconds


**Element-wise Multiplication**

In [31]:

# Number of elements in the lists
size = 1_000_000

# Create two Python lists
list1 = list(range(size))
list2 = list(range(size))

# Measure the time taken for element-wise multiplication using Python lists
start_time = time.time()
list3 = [a * b for a, b in zip(list1, list2)]
end_time = time.time()
list_time = end_time - start_time
print(f"Time taken for list multiplication: {list_time:.6f} seconds")

# Create two NumPy arrays
array1 = np.arange(size)
array2 = np.arange(size)

# Measure the time taken for element-wise multiplication using NumPy arrays
start_time = time.time()
array3 = array1 * array2  # Faster element-wise multiplication with NumPy
end_time = time.time()
numpy_time = end_time - start_time
print(f"Time taken for NumPy array multiplication: {numpy_time:.6f} seconds")


Time taken for list multiplication: 0.043011 seconds
Time taken for NumPy array multiplication: 0.001140 seconds


**Dot Product**

In [41]:


# Number of elements in the lists
size = 1_000_000

# Using Python Lists
list1 = list(range(size))
list2 = list(range(size))

start_time = time.time()
dot_product_list = sum(a * b for a, b in zip(list1, list2))
end_time = time.time()
list_time = end_time - start_time

print(f"Dot product (Python lists): {dot_product_list}")
print(f"Time taken (Python lists): {list_time:.6f} seconds")


# Using NumPy Arrays
array1 = np.arange(size)
array2 = np.arange(size)

start_time = time.time()
dot_product_np = np.dot(array1, array2)
end_time = time.time()
numpy_time = end_time - start_time

print(f"\nDot product (NumPy arrays): {dot_product_np}")
print(f"Time taken (NumPy arrays): {numpy_time:.6f} seconds")


Dot product (Python lists): 333332833333500000
Time taken (Python lists): 0.049731 seconds

Dot product (NumPy arrays): 333332833333500000
Time taken (NumPy arrays): 0.000824 seconds


**Matrix Multiplication**

In [43]:

import numpy as np
import time

# Matrix multiplication using Python lists
def matrix_multiply_list(A, B):
    rows_A = len(A)
    cols_A = len(A[0])
    rows_B = len(B)
    cols_B = len(B[0])

    if cols_A != rows_B:
        raise ValueError("Matrices cannot be multiplied")

    result = [[0 for _ in range(cols_B)] for _ in range(rows_A)]
    for i in range(rows_A):
        for j in range(cols_B):
            for k in range(cols_A):
                result[i][j] += A[i][k] * B[k][j]
    return result

# Matrix multiplication using NumPy
def matrix_multiply_numpy(A, B):
    return np.dot(A,B)

# Generate random matrices of size 1000x1000
size = 1000
matrix_a = [[np.random.randint(0,10) for _ in range(size)] for _ in range(size)]
matrix_b = [[np.random.randint(0,10) for _ in range(size)] for _ in range(size)]

# Python list multiplication
start_time = time.time()
matrix_multiply_list(matrix_a, matrix_b)
end_time = time.time()
print(f"Time taken for Python list matrix multiplication: {end_time - start_time:.6f} seconds")

# Convert lists to numpy arrays
matrix_a_np = np.array(matrix_a)
matrix_b_np = np.array(matrix_b)

# NumPy matrix multiplication
start_time = time.time()
matrix_multiply_numpy(matrix_a_np, matrix_b_np)
end_time = time.time()
print(f"Time taken for NumPy matrix multiplication: {end_time - start_time:.6f} seconds")


Time taken for Python list matrix multiplication: 87.342400 seconds
Time taken for NumPy matrix multiplication: 0.830194 seconds
